# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addfile_btn = QtWidgets.QPushButton(Form)
        self.addfile_btn.setObjectName("addfile_btn")
        self.horizontalLayout_5.addWidget(self.addfile_btn)
        self.addfolder_btn = QtWidgets.QPushButton(Form)
        self.addfolder_btn.setObjectName("addfolder_btn")
        self.horizontalLayout_5.addWidget(self.addfolder_btn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.preset_cobox = QtWidgets.QComboBox(Form)
        self.preset_cobox.setMaxVisibleItems(11)
        self.preset_cobox.setObjectName("preset_cobox")
        self.preset_cobox.addItem("")
        self.horizontalLayout_4.addWidget(self.preset_cobox)
        self.x_btn = QtWidgets.QPushButton(Form)
        self.x_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.x_btn.setText("")
        self.x_btn.setIconSize(QtCore.QSize(20, 20))
        self.x_btn.setFlat(True)
        self.x_btn.setObjectName("x_btn")
        self.horizontalLayout_4.addWidget(self.x_btn)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.log_cobox = QtWidgets.QComboBox(Form)
        self.log_cobox.setMaxVisibleItems(11)
        self.log_cobox.setObjectName("log_cobox")
        self.log_cobox.addItem("")
        self.horizontalLayout_5.addWidget(self.log_cobox)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.name_LE = QtWidgets.QLineEdit(Form)
        self.name_LE.setObjectName("name_LE")
        self.horizontalLayout_2.addWidget(self.name_LE)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.serial_LE = QtWidgets.QLineEdit(Form)
        self.serial_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.serial_LE.setMaxLength(6)
        self.serial_LE.setObjectName("serial_LE")
        self.horizontalLayout_2.addWidget(self.serial_LE)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.ext_LE = QtWidgets.QLineEdit(Form)
        self.ext_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ext_LE.setObjectName("ext_LE")
        self.horizontalLayout_2.addWidget(self.ext_LE)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.order_LE = QtWidgets.QLineEdit(Form)
        self.order_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.order_LE.setMaxLength(6)
        self.order_LE.setObjectName("order_LE")
        self.horizontalLayout.addWidget(self.order_LE)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fansub_LE = QtWidgets.QLineEdit(Form)
        self.fansub_LE.setObjectName("fansub_LE")
        self.horizontalLayout.addWidget(self.fansub_LE)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.delay_LE = QtWidgets.QLineEdit(Form)
        self.delay_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delay_LE.setMaxLength(8)
        self.delay_LE.setObjectName("delay_LE")
        self.horizontalLayout.addWidget(self.delay_LE)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lang_cobox = QtWidgets.QComboBox(Form)
        self.lang_cobox.setObjectName("lang_cobox")
        self.lang_cobox.addItem("")
        self.lang_cobox.setItemText(0, "")
        self.lang_cobox.addItem("")
        self.lang_cobox.addItem("")
        self.lang_cobox.addItem("")
        self.horizontalLayout.addWidget(self.lang_cobox)
        self.erase_btn = QtWidgets.QPushButton(Form)
        self.erase_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.erase_btn.setText("")
        self.erase_btn.setIconSize(QtCore.QSize(20, 20))
        self.erase_btn.setFlat(True)
        self.erase_btn.setObjectName("erase_btn")
        self.horizontalLayout.addWidget(self.erase_btn)
        self.addpreset_btn = QtWidgets.QPushButton(Form)
        self.addpreset_btn.setObjectName("addpreset_btn")
        self.horizontalLayout.addWidget(self.addpreset_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setEnabled(False)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.date_chbox = QtWidgets.QCheckBox(Form)
        self.date_chbox.setObjectName("date_chbox")
        self.horizontalLayout_3.addWidget(self.date_chbox)
        self.type_chbox = QtWidgets.QCheckBox(Form)
        self.type_chbox.setObjectName("type_chbox")
        self.horizontalLayout_3.addWidget(self.type_chbox)
        spacerItem = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 4, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setObjectName("tableView")
        self.gridLayout_2.addWidget(self.tableView, 4, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rename_btn = QtWidgets.QPushButton(Form)
        self.rename_btn.setObjectName("rename_btn")
        self.gridLayout.addWidget(self.rename_btn, 0, 0, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(Form)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 0, 2, 1, 1)
        self.unrename_btn = QtWidgets.QPushButton(Form)
        self.unrename_btn.setObjectName("unrename_btn")
        self.gridLayout.addWidget(self.unrename_btn, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 5, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addfile_btn.setText(_translate("Form", "Add File(s)"))
        self.addfolder_btn.setText(_translate("Form", "Add Folder"))
        self.preset_cobox.setItemText(0, _translate("Form", "Preset(s)"))
        self.x_btn.setToolTip(_translate("Form", "Delete the seleceted preset."))
        self.log_cobox.setItemText(0, _translate("Form", "Log History"))
        self.label.setText(_translate("Form", "Name:"))
        self.name_LE.setPlaceholderText(_translate("Form", "File Name ex. My_File"))
        self.label_5.setText(_translate("Form", "Serialize:"))
        self.serial_LE.setPlaceholderText(_translate("Form", "1or01..."))
        self.label_7.setText(_translate("Form", "Ext:"))
        self.ext_LE.setPlaceholderText(_translate("Form", "mkv,exe"))
        self.label_3.setText(_translate("Form", "Order:"))
        self.order_LE.setPlaceholderText(_translate("Form", "01 ..."))
        self.label_2.setText(_translate("Form", "Fan-Sub Team:"))
        self.fansub_LE.setPlaceholderText(_translate("Form", "Fan-Sub Team Name"))
        self.label_4.setText(_translate("Form", "Delay (ms):"))
        self.delay_LE.setPlaceholderText(_translate("Form", "1000"))
        self.label_6.setText(_translate("Form", "Lang:"))
        self.lang_cobox.setItemText(1, _translate("Form", "Ara"))
        self.lang_cobox.setItemText(2, _translate("Form", "Eng"))
        self.lang_cobox.setItemText(3, _translate("Form", "Jap"))
        self.erase_btn.setToolTip(_translate("Form", "Erase All The Fileds text."))
        self.addpreset_btn.setText(_translate("Form", "Add Preset"))
        self.label_8.setText(_translate("Form", "Original Name(s)"))
        self.date_chbox.setText(_translate("Form", "Date"))
        self.type_chbox.setText(_translate("Form", "Type"))
        self.rename_btn.setText(_translate("Form", "Rename"))
        self.clear_btn.setText(_translate("Form", "Clear Lists"))
        self.unrename_btn.setText(_translate("Form", "UnRename"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
