# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\H.Ali\Desktop\python test\Rename\UI\maingui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 690)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 120, 391, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(10, 140, 631, 541))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.widget1)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_4.addWidget(self.listWidget)
        self.listView = QtWidgets.QListView(self.widget1)
        self.listView.setObjectName("listView")
        self.horizontalLayout_4.addWidget(self.listView)
        self.widget2 = QtWidgets.QWidget(Form)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 631, 25))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addfile_btn = QtWidgets.QPushButton(self.widget2)
        self.addfile_btn.setObjectName("addfile_btn")
        self.horizontalLayout_5.addWidget(self.addfile_btn)
        self.addfolder_btn = QtWidgets.QPushButton(self.widget2)
        self.addfolder_btn.setObjectName("addfolder_btn")
        self.horizontalLayout_5.addWidget(self.addfolder_btn)
        self.preview_btn = QtWidgets.QPushButton(self.widget2)
        self.preview_btn.setObjectName("preview_btn")
        self.horizontalLayout_5.addWidget(self.preview_btn)
        self.rename_btn = QtWidgets.QPushButton(self.widget2)
        self.rename_btn.setObjectName("rename_btn")
        self.horizontalLayout_5.addWidget(self.rename_btn)
        self.widget3 = QtWidgets.QWidget(Form)
        self.widget3.setGeometry(QtCore.QRect(12, 51, 631, 52))
        self.widget3.setObjectName("widget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_LE = QtWidgets.QLineEdit(self.widget3)
        self.name_LE.setObjectName("name_LE")
        self.horizontalLayout.addWidget(self.name_LE)
        self.label_5 = QtWidgets.QLabel(self.widget3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.serial_LE = QtWidgets.QLineEdit(self.widget3)
        self.serial_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.serial_LE.setObjectName("serial_LE")
        self.horizontalLayout.addWidget(self.serial_LE)
        self.label_7 = QtWidgets.QLabel(self.widget3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.ext_LE = QtWidgets.QLineEdit(self.widget3)
        self.ext_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ext_LE.setObjectName("ext_LE")
        self.horizontalLayout.addWidget(self.ext_LE)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.order_LE = QtWidgets.QLineEdit(self.widget3)
        self.order_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.order_LE.setObjectName("order_LE")
        self.horizontalLayout_2.addWidget(self.order_LE)
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.fansub_LE = QtWidgets.QLineEdit(self.widget3)
        self.fansub_LE.setObjectName("fansub_LE")
        self.horizontalLayout_2.addWidget(self.fansub_LE)
        self.label_4 = QtWidgets.QLabel(self.widget3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.delay_LE = QtWidgets.QLineEdit(self.widget3)
        self.delay_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delay_LE.setObjectName("delay_LE")
        self.horizontalLayout_2.addWidget(self.delay_LE)
        self.label_6 = QtWidgets.QLabel(self.widget3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lang_chbox = QtWidgets.QComboBox(self.widget3)
        self.lang_chbox.setObjectName("lang_chbox")
        self.lang_chbox.addItem("")
        self.lang_chbox.setItemText(0, "")
        self.lang_chbox.addItem("")
        self.lang_chbox.addItem("")
        self.lang_chbox.addItem("")
        self.horizontalLayout_2.addWidget(self.lang_chbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "Original Name(s):"))
        self.label_9.setText(_translate("Form", "New Name(s):"))
        self.addfile_btn.setText(_translate("Form", "Add File(s)"))
        self.addfolder_btn.setText(_translate("Form", "Add Folder"))
        self.preview_btn.setText(_translate("Form", "Preview"))
        self.rename_btn.setText(_translate("Form", "Rename"))
        self.label.setText(_translate("Form", "Name:"))
        self.name_LE.setPlaceholderText(_translate("Form", "File Name ex. My_File"))
        self.label_5.setText(_translate("Form", "Serialize:"))
        self.serial_LE.setPlaceholderText(_translate("Form", "1or01..."))
        self.label_7.setText(_translate("Form", "Ext:"))
        self.ext_LE.setPlaceholderText(_translate("Form", "mkv,exe"))
        self.label_3.setText(_translate("Form", "Order:"))
        self.order_LE.setPlaceholderText(_translate("Form", "01 ..."))
        self.label_2.setText(_translate("Form", "Fan-Sub Team:"))
        self.fansub_LE.setPlaceholderText(_translate("Form", "Fan-Sub Team Name"))
        self.label_4.setText(_translate("Form", "Delay (ms):"))
        self.delay_LE.setPlaceholderText(_translate("Form", "1000"))
        self.label_6.setText(_translate("Form", "Lang:"))
        self.lang_chbox.setItemText(1, _translate("Form", "Ara"))
        self.lang_chbox.setItemText(2, _translate("Form", "Eng"))
        self.lang_chbox.setItemText(3, _translate("Form", "Jap"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
